"""posts table

Revision ID: e72c39b2427c
Revises: d3e4b8478090
Create Date: 2019-03-02 17:47:25.101756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72c39b2427c'
down_revision = 'd3e4b8478090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('use_type', sa.String(length=140), nullable=True))
    op.drop_column('post', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('post', 'use_type')
    # ### end Alembic commands ###
